development:
    site_name: Threesuns
    owner_email: xxx@xxx.xxx
    site_url: http://localhost:3000
    host: threesuns.org
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
    
test:
    site_name: Threesuns.org
    owner_email: xxx@xxx.xxx
    rake_path: /usr/local/bin/rake
    host: localhost:3000
    site_url: http://localhost:3000

production:
    site_name: Threesuns
    owner_email: xxx@xxx.xxx
    site_url: http://threesuns.org
    host: threesuns.org
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
