development:
    site_name: Threesuns<span>.</span>org
    owner_email: xxx@xxx.xxx
    banner_location: http://localhost:3000/images/sml_banner.png
    site_url: http://localhost:3000
    host: threesuns.org
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger
    
test:
    site_name: Threesuns.org
    owner_email: xxx@xxx.xxx
    rake_path: /usr/local/bin/rake
    host: localhost:3000
    site_url: http://localhost:3000
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger

production:
    site_name: Threesuns<span>.</span>org
    owner_email: xxx@xxx.xxx
    banner_location: http://suchnull.com/images/sml_banner.png
    site_url: http://threesuns.org
    host: threesuns.org
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger
