development:
    site_name: Threesuns
    owner_email: xxx@xxx.xxx
    banner_location: http://localhost:3000/images/sml_banner.png
    site_url: http://localhost:3000
    host: localhost:3000
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger
    
test:
    site_name: Ingeni<span>o.</span>us
    owner_email: xxx@xxx.xxx
    rake_path: /usr/local/bin/rake
    host: localhost:3000
    site_url: http://localhost:3000
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger

production:
    site_name: suchnull 
    owner_email: xxx@xxx.xxx
    banner_location: http://suchnull.com/images/sml_banner.png
    site_url: http://suchnull.com
    host: suchnull.com
    rake_path: /usr/bin/rake
    ted_username: USERNAMEREMOVED
    ted_password: "ADMINPASSWORD"
    bitly_api_key: R_6fb60eaabee27d77bb380210c7f0e1b3
    bitly_username: noahsinger
